import { useMemo, useRef, useState } from 'react';
import type { Difficulty, FunFact, WritingExercise } from '../types/content';
import { byDifficulty, normalizeAnswer, randomItem } from '../utils/game';
import { Feedback, GameLayout, ReadAloudButton } from './Common';

export function WritingGame({ difficulty, exercises, facts, score, best, onCorrect, onHome, onRequestNext, contextLabel }: { difficulty: Difficulty; exercises: WritingExercise[]; facts: FunFact[]; score: number; best: number; onCorrect: () => void; onHome: () => void; onRequestNext?: () => void; contextLabel?: string }) {
  const available = useMemo(() => byDifficulty(exercises, difficulty), [exercises, difficulty]);
  const solvedRef = useRef(false);
  const [exercise, setExercise] = useState(() => randomItem(available)); const [kind, setKind] = useState<'listen' | 'complete'>(() => Math.random() > .5 ? 'listen' : 'complete'); const [value, setValue] = useState(''); const [feedback, setFeedback] = useState<'correct' | 'wrong' | null>(null); const [attempts, setAttempts] = useState(0); const [hint, setHint] = useState(0); const [fact, setFact] = useState('');
  if (!exercise) return <GameLayout score={score} best={best} onHome={onHome} title="Scrittura" icon="✏️"><p className="empty-message">Le parole stanno arrivando! Prova un altro livello.</p></GameLayout>;
  const missingAnswer = exercise.completeWord.missingLetters.join('');
  const expectedAnswer = kind === 'complete' ? missingAnswer : exercise.word;
  const missingCount = exercise.completeWord.missingLetters.length;
  const check = () => { if (!value || solvedRef.current || feedback === 'correct') return; if (normalizeAnswer(value) === normalizeAnswer(expectedAnswer)) { solvedRef.current = true; setFeedback('correct'); setFact(facts.length ? randomItem(facts).text : 'Ogni parola scritta è una piccola conquista!'); onCorrect(); } else { setAttempts(a => a + 1); setFeedback('wrong'); setHint(h => Math.max(h, attempts >= 1 ? 2 : 1)); } };
  const next = () => { solvedRef.current = false; if (onRequestNext) { onRequestNext(); return; } setExercise(randomItem(available)); setKind(Math.random() > .5 ? 'listen' : 'complete'); setValue(''); setFeedback(null); setAttempts(0); setHint(0); };
  return <GameLayout score={score} best={best} onHome={onHome} title="Scrittura" icon="✏️">{contextLabel && <div className="mix-badge">🔀 {contextLabel}</div>}<section className="quiz-card writing-card"><p className="instruction">{kind === 'listen' ? 'Ascolta e scrivi la parola' : `Scrivi ${missingCount === 1 ? 'la lettera' : 'le lettere'} che ${missingCount === 1 ? 'manca' : 'mancano'}`}</p><div className="word-support">{difficulty !== 'difficile' && <span>{exercise.emoji}</span>}<strong>{kind === 'complete' ? exercise.completeWord.masked : '🔊'}</strong></div><ReadAloudButton text={exercise.word} label="Ascolta la parola" />
    {hint > 0 && <div className="hint" role="status">{kind === 'complete' ? <>💡 Dilla a pezzetti: <strong>{exercise.syllables.join(' - ')}</strong>{hint > 1 && <> · {missingCount === 1 ? 'Manca' : 'Mancano'}: <strong>{exercise.completeWord.missingLetters.join(' · ')}</strong></>}</> : <>💡 Inizia con <strong>{exercise.word[0]}</strong>{hint > 1 && <> · Dilla a pezzetti: <strong>{exercise.syllables.join(' - ')}</strong></>}</>}</div>}
    <label className="sr-only" htmlFor="word-input">{kind === 'complete' ? 'Scrivi ciò che manca' : 'Scrivi la parola'}</label><input id="word-input" className="word-input" autoComplete="off" autoCapitalize="characters" maxLength={kind === 'complete' ? missingCount : exercise.word.length} value={value} disabled={feedback === 'correct'} onChange={e => setValue(e.target.value)} onKeyDown={e => e.key === 'Enter' && check()} placeholder={kind === 'complete' ? (missingCount === 1 ? 'Una lettera…' : 'Le lettere…') : 'Scrivi qui…'} />
    <div className="writing-actions"><button className="help-button" disabled={feedback === 'correct'} onClick={() => setHint(h => Math.min(2, h + 1))}>💡 Aiuto</button><button className="primary-button" disabled={!value || feedback === 'correct'} onClick={check}>Controlla ✓</button></div>
    <Feedback state={feedback} message={feedback === 'correct' ? (kind === 'complete' ? 'Parola completata!' : 'Scritta benissimo!') : attempts >= 2 ? (kind === 'complete' ? `La parola completa è ${exercise.word}. Scrivi solo ciò che manca.` : `La parola è ${exercise.word}. Riproviamo insieme!`) : (kind === 'complete' ? 'Quasi! Guarda lo spazio vuoto.' : 'Quasi! Ascolta ancora.')} fact={fact} onNext={next} nextLabel="Nuova parola" />
  </section></GameLayout>;
}
